dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/3.3.1/bazel_3.3.1-linux-x86_64.deb
  - sudo dpkg -i bazel_3.3.1-linux-x86_64.deb

script:
  - chmod +x ./check_lint.sh && ./check_lint.sh
  - chmod +x ./check_tests.sh && ./check_tests.sh
