dist: xenial
language: python
python: '3.7'
branches:
  only:
  - master
env:
  global:
    secure: N2znTSyEsm8ksfdkCb5KeSmrCyuI6ol7T+xLkTG0SQKcUSXH5ohH8NFmZVPe/d/3AYICKuWz8aCuKimNGPpBmNa4acZuyrqsD+WQw3DQLwBMaOLbws2rYb7Kig37L56SUKqVDN55toYoAnZOAxI3+j17SfkE0l1IDUD9W1xejtG1UyDFJj4rXAr9tVJqQOCkzfhpCl6o3MI5JRwwaD7CRKm2NxthgB9eCMPEhuCInoM3/mei7U4Om09apZj2fJBmAE/6qdan3BHyT7uGJwOL5bk3baGHUAUaDiM5I9EqI1t2dX63caObX4T8vz0akEkQQ2yeOhL99bCl7HwTDWRRr52nk0Gy9j62o3T+1rW5chmt+1jNLCeB9pZUFxsedIXfb5YRcVpN8xOSI35r7g/a1tVlhL1NncobaBk9JbRJE527qVTROjM1hXZNCk9l67lvSWZdm/Yi5iTuuManMAHReYnHOE3Q+yfEL4UhyEAVEs2q9VZOOv3Hmh5Hda6iNo2JYly+JXyqUH4OYa95upAcDXddAGhmhNyTa2LzB9Nci0z3lvMdjAzpxAQ7d0duGyTZangiMntNIrIoxpR5SPbn5pupcXeHt8svLOXW3QNl3Q0ToIeOOeoVt5vqvI5uEMJjd/fnNXGRpDrF/dGnOkYb2JPS4aQtGuHW7GjBM2mzz3g=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - wget
    - pkg-config
before_install:
- wget https://github.com/bazelbuild/bazel/releases/download/3.3.1/bazel_3.3.1-linux-x86_64.deb
- sudo dpkg -i bazel_3.3.1-linux-x86_64.deb
script:
- test $TRAVIS_EVENT_TYPE = "push" && test $TRAVIS_BRANCH = "master" || ./check_lint.sh
- test $TRAVIS_EVENT_TYPE = "push" && test $TRAVIS_BRANCH = "master" || ./check_tests.sh
after_success:
- test $TRAVIS_EVENT_TYPE = "push" && test $TRAVIS_BRANCH = "master" && ./deploy.sh
