load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")

package(default_visibility = ["//visibility:public"])

py_proto_library(
    name = "rated_player",
    srcs = [
        "aza.propo",
        "rated_player.proto",
    ],
)
